Algoritmo "Aula2 Introdução"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/10/2022
Var
idade: inteiro


Inicio
escreva("Digite sua idade ?")
leia(idade)

se idade >= 18 entao
escreva ("Você tem 18 anos ou mais ")
fimse

Fimalgoritmo